language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget http://github.com/erpcya/adempiere/releases/latest/download/Adempiere_393LTS.tar.gz -c -O Adempiere.tar.gz
  - tar -xzf Adempiere.tar.gz
  - mv Adempiere/lib/Adempiere.jar dependences/Adempiere.jar
  - mv Adempiere/packages/HumanResourceAndPayroll/lib/HumanResourceAndPayroll.jar dependences/HumanResourceAndPayroll.jar
  - wget http://github.com/erpcya/Withholding/releases/latest/download/Withholding.zip -c -O Withholding.zip
  - mkdir references
  - unzip -o Withholding.zip -d references
  - unzip -o references/build/release/Withholding.zip -d references/build/release/
  - mv references/build/release/*.jar dependences/
jobs:
  include:
    - stage: Compilation
      script: ./gradlew build
    - stage: Prepare Release
      script:
         - ./gradlew build 
         - ./gradlew createRelease
      on:
       tags: true
deploy:
  provider: releases
  token: $GITHUB_TOKEN_KEY
  skip_cleanup: true
  file: 
    - "$TRAVIS_BUILD_DIR/build/release/LVE.zip"
    - "$TRAVIS_BUILD_DIR/build/release/LVE.zip.MD5"
  on:
    tags: true